version: '3.8'

services:
  clouddisk:
    build:
      context: .
      dockerfile: CloudFileHub/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=CloudFileHub;User=root;Password=123456;
    volumes:
      - file_uploads:/app/wwwroot/uploads
    networks:
      - cloudfilehub_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: CloudFileHub
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cloudfilehub_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456
    depends_on:
      - mysql
    networks:
      - cloudfilehub_network

volumes:
  mysql_data:
  file_uploads:

networks:
  cloudfilehub_network:
    driver: bridge